apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        ports:
        - name: "uimport"
          containerPort: 15672
        - name: "mport"
          containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rmq-load
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
  - name: "uimport"
    port: 15672
    targetPort: 15672
  - name: "mport"
    port: 5672
    targetPort: 5672
